version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=monitoring-service
      - MARIADB_PASSWORD=qwerty123

  app:
    tty: true
    image: docker.io/bitnami/laravel:8-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=admin
      - DB_DATABASE=monitoring-service
      - DB_PASSWORD=qwerty123
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
